# PANDAS

Pandas Series/Dataframe created by loading the datasets from existing storage, storage can be SQL Database, CSV file, an Excel file. 

Pandas Series/Dataframe can be created from the lists, dictionary, and from a scalar value etc.

### Creating a Series

In [2]:
import pandas as pd
import numpy as np
 
 
# Creating empty series
ser = pd.Series()
   
print(ser)
 
# simple array
data = np.array(['A', 'r', 'o', 's', 'e'])
   
ser = pd.Series(data)
print(ser)

Series([], dtype: float64)
0    A
1    r
2    o
3    s
4    e
dtype: object


<ipython-input-2-14f7427511b1>:6: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  ser = pd.Series()


### Creating a DataFrame:
 

In [5]:
import pandas as pd
   
# Calling DataFrame constructor
df = pd.DataFrame()
print(df)
 
# list of strings
lst = ['Mai', 'ja', 'rahi', 'hu', 
            'portal', 'use', 'karne']
   
# Calling DataFrame constructor on list
df = pd.DataFrame(lst)
print(df)

Empty DataFrame
Columns: []
Index: []
        0
0     Mai
1      ja
2    rahi
3      hu
4  portal
5     use
6   karne


Method #0: Creating an Empty DataFrame

In [7]:
# Creating Empty DataFrame and Storing it in variable df
df = pd.DataFrame()
  
# Printing Empty DataFrame
print(df)

Empty DataFrame
Columns: []
Index: []


Method #1: Creating  Dataframe from Lists

In [9]:
# initialize list elements
data = [10,20,30,40,50,60]
  
# Create the pandas DataFrame with column name is provided explicitly
df = pd.DataFrame(data, columns=['Numbers'])
  
# print dataframe.
df

Numbers
0       10
1       20
2       30
3       40
4       50
5       60

Method #2: Creating Pandas DataFrame from lists of lists.

In [10]:
# initialize list of lists
data = [['tom', 10], ['nick', 15], ['juli', 14]]
  
# Create the pandas DataFrame
df = pd.DataFrame(data, columns=['Name', 'Age'])
  
# print dataframe.
df

Name  Age
0   tom   10
1  nick   15
2  juli   14

Method #3: Creating DataFrame from dict of narray/lists
To create DataFrame from dict of narray/list, all the narray must be of same length. If index is passed then the length index should be equal to the length of arrays. If no index is passed, then by default, index will be range(n) where n is the array length.

In [11]:
# initialize data of lists.
data = {'Name': ['Tom', 'nick', 'krish', 'jack'],
        'Age': [20, 21, 19, 18]}
  
# Create DataFrame
df = pd.DataFrame(data)
  
# Print the output.
df

Name  Age
0    Tom   20
1   nick   21
2  krish   19
3   jack   18

Method #4: Creating a DataFrame by proving index label explicitly.

In [12]:
# initialize data of lists.
data = {'Name': ['Tom', 'Jack', 'nick', 'juli'],
        'marks': [99, 98, 95, 90]}
  
# Creates pandas DataFrame.
df = pd.DataFrame(data, index=['rank1',
                               'rank2',
                               'rank3',
                               'rank4'])
  
# print the data
df

Name  marks
rank1   Tom     99
rank2  Jack     98
rank3  nick     95
rank4  juli     90

Method #5: Creating Dataframe from list of dicts

Pandas DataFrame can be created by passing lists of dictionaries as a input data. By default dictionary keys will be taken as columns.

In [13]:
# Initialize data to lists.
data = [{'a': 1, 'b': 2, 'c': 3},
        {'a': 10, 'b': 20, 'c': 30}]
  
# Creates DataFrame.
df = pd.DataFrame(data)
  
# Print the data
df

a   b   c
0   1   2   3
1  10  20  30

create pandas DataFrame from lists of dictionaries with both row index as well as column index.

In [14]:
# Initialize lists data.
data = [{'a': 1, 'b': 2},
        {'a': 5, 'b': 10, 'c': 20}]
  
# With two column indices, values same
# as dictionary keys
df1 = pd.DataFrame(data, index=['first',
                                'second'],
                   columns=['a', 'b'])
  
# With two column indices with
# one index with other name
df2 = pd.DataFrame(data, index=['first',
                                'second'],
                   columns=['a', 'b1'])
  
# print for first data frame
print(df1, "\n")
  
# Print for second DataFrame.
print(df2)

        a   b
first   1   2
second  5  10 

        a  b1
first   1 NaN
second  5 NaN


Method #6: Creating DataFrame using zip() function.

Two lists can be merged by using list(zip()) function. Now, create the pandas DataFrame by calling pd.DataFrame() function.

In [15]:
# List1
Name = ['tom', 'krish', 'nick', 'juli']
  
# List2
Age = [25, 30, 26, 22]
  
# get the list of tuples from two lists.
# and merge them by using zip().
list_of_tuples = list(zip(Name, Age))
  
# Assign data to tuples.
list_of_tuples
  
  
# Converting lists of tuples into
# pandas Dataframe.
df = pd.DataFrame(list_of_tuples,
                  columns=['Name', 'Age'])
  
# Print data.
df

Name  Age
0    tom   25
1  krish   30
2   nick   26
3   juli   22

Method#7:  Creating dataframe from series

To create a dataframe from series, we must pass series as argument to DataFrame() function.

In [16]:
# Initialize data to series.
d =  pd.Series([10, 20, 30, 40])
# creates Dataframe.
df = pd.DataFrame(d)
  
# print the data.
df

0
0  10
1  20
2  30
3  40

Method #8: Creating DataFrame from Dictionary of series.

To create DataFrame from Dict of series, dictionary can be passed to form a DataFrame. The resultant index is the union of all the series of passed indexed.
 

In [17]:
# Initialize data to Dicts of series.
d = {'one': pd.Series([10, 20, 30, 40],
                      index=['a', 'b', 'c', 'd']),
     'two': pd.Series([10, 20, 30, 40],
                      index=['a', 'b', 'c', 'd'])}
  
# creates Dataframe.
df = pd.DataFrame(d)
  
# print the data.
df

one  two
a   10   10
b   20   20
c   30   30
d   40   40

## Series

Creating a series from array: In order to create a series from array, we have to import a numpy module and have to use array() function.



In [18]:
import pandas as pd
 
# import numpy as np
import numpy as np
 
# simple array
data = np.array(['j','e','r','k','s'])
 
ser = pd.Series(data)
print(ser)

0    j
1    e
2    r
3    k
4    s
dtype: object


Accessing element of Series
There are two ways through which we can access element of series, they are :

Accessing Element from Series with Position
Accessing Element Using Label (index)
Accessing Element from Series with Position : In order to access the series element refers to the index number. Use the index operator [ ] to access an element in a series. The index must be an integer. In order to access multiple elements from a series, we use Slice operation.

In [19]:
data = np.array(['j','e','r','k','s','f', 'o','r','m','e'])
ser = pd.Series(data)
  
  
#retrieve the first element
print(ser[:5])

0    j
1    e
2    r
3    k
4    s
dtype: object


Accessing Element Using Label (index) :
In order to access an element from series, we have to set values by index label. A Series is like a fixed-size dictionary in that you can get and set values by index label.

Accessing a single element using index label

In [22]:
data = np.array(['j','e','r','k','s','f', 'o','r','m','e'])
ser = pd.Series(data,index=[10,11,12,13,14,15,16,17,18,19])
  
  
# accessing a element using index element
print(ser[16])

o


Indexing and Selecting Data in Series
Indexing in pandas means simply selecting particular data from a Series. Indexing could mean selecting all the data, some of the data from particular columns. Indexing can also be known as Subset Selection.

Indexing a Series using indexing operator [] :
Indexing operator is used to refer to the square brackets following an object. The .loc and .iloc indexers also use the indexing operator to make selections. In this indexing operator to refer to df[ ].

Binary Operation on Series

We can perform binary operation on series like addition, subtraction and many other operation. In order to perform binary operation on series we have to use some function like .add(),.sub() etc..

Conversion Operation on Series

In conversion operation we perform various operation like changing datatype of series, changing a series to list etc. In order to perform conversion operation we have various function which help in conversion like .astype(), .tolist() etc.

#### Python program using astype
#### to convert a datatype of series
 
#### importing pandas module  
import pandas as pd 
   
#### reading csv file from url  
data = pd.read_csv("filename.csv") 
    
#### dropping null value columns to avoid errors 
data.dropna(inplace = True) 
   
#### storing dtype before converting 
before = data.dtypes 
   
#### converting dtypes using astype 
data["Salary"]= data["Salary"].astype(int) 
data["Number"]= data["Number"].astype(str) 
   
#### storing dtype after converting 
after = data.dtypes 
   
#### printing to compare 
print("BEFORE CONVERSION\n", before, "\n") 
print("AFTER CONVERSION\n", after, "\n") 

Convert DataFrame to Numpy Array

In [24]:
# initialize a dataframe
df = pd.DataFrame(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9],
     [10, 11, 12]],
    columns=['a', 'b', 'c'])
 
# convert dataframe to numpy array
arr = df.to_numpy()
 
print('\nNumpy Array\n----------\n', arr)
print(type(arr))


Numpy Array
----------
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
<class 'numpy.ndarray'>


Example #1: Use Series.as_matrix() function to return the numpy-array representation of the given series object.

In [29]:
# Creating the Series
sr = pd.Series(['New York', 'Chicago', 'Toronto', 'Lisbon', 'Rio'])
  
# Create the Index
index_ = ['City 1', 'City 2', 'City 3', 'City 4', 'City 5'] 
  
# set the index
sr.index = index_
  
# Print the series
print(sr)

City 1    New York
City 2     Chicago
City 3     Toronto
City 4      Lisbon
City 5         Rio
dtype: object


use Series.as_matrix() function to return the numpy array representation of the given series object.

Example passes a function and checks the value of each element in series and returns low, normal or High accordingly.

import pandas as pd
  
##### reading csv
s = pd.read_csv("file_name.csv", squeeze = True)
  
#### defining function to check price
def fun(num):
  
    if num<200:
        return "Low"
  
    elif num>= 200 and num<400:
        return "Normal"
  
    else:
        return "High"
  
##### passing function to apply and storing returned series in new
new = s.apply(fun)
  
##### printing first 3 element
print(new.head(3))
  
##### printing elements somewhere near the middle of series
print(new[1400], new[1500], new[1600])
  
##### printing last 3 elements
print(new.tail(3))